github: "your-github-username"
patreon: "your-patreon-id"
open_collective: "your-open-collective-id"
ko_fi: "your-ko-fi-id"
tidelift: "npm/your-package-name"
community_bridge: "your-community-bridge-id"
issuehunt: "your-issuehunt-id"
liberapay: "private-data-storage-unit-secure-access"
polar: "your-polar-id"
buy_me_a_coffee: "default-id"
thanks_dev: "u/gh/your-thanks-dev-id"
custom: "https://your-custom-funding-url.example.com"
